/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.sql.*;
import config.Conexio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1999s
 */
public class JFrameEmpreses extends javax.swing.JFrame {
 Conexio con = new Conexio();
 Connection cn;
 Statement st;
 ResultSet rs;
 DefaultTableModel modelo;
 int id;
    /**
     * Creates new form Principal
     */
    public JFrameEmpreses() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnnou1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtlocalitat = new javax.swing.JTextField();
        txtdireccio = new javax.swing.JTextField();
        txtcif = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        telefon = new javax.swing.JLabel();
        txttelefon = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnafegir = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnnou = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tauladades = new javax.swing.JTable();
        btnenrere = new javax.swing.JButton();

        btnnou1.setText("Nou");
        btnnou1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnou1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestió Empreses");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dades"));

        jLabel2.setText("Nom:");

        jLabel3.setText("Localitat:");

        jLabel4.setText("Direcció:");

        jLabel5.setText("CIF:");

        jLabel6.setText("Email:");

        txtdireccio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccioActionPerformed(evt);
            }
        });

        txtcif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcifActionPerformed(evt);
            }
        });

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        telefon.setText("Telefon:");

        txttelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                            .addComponent(txtlocalitat)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtcif, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdireccio, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telefon)
                        .addGap(18, 18, 18)
                        .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtlocalitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdireccio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefon)
                    .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operacions"));

        btnafegir.setText("Afegir");
        btnafegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnafegirActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnnou.setText("Nou");
        btnnou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnafegir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnafegir)
                    .addComponent(btneditar)
                    .addComponent(btneliminar)
                    .addComponent(btnnou))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Llistat d'empreses"));

        tauladades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom", "localitat", "direccio", "telefon", "cif", "email", "estat"
            }
        ));
        tauladades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tauladadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tauladades);
        if (tauladades.getColumnModel().getColumnCount() > 0) {
            tauladades.getColumnModel().getColumn(0).setMinWidth(50);
            tauladades.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );

        btnenrere.setText("Enrere");
        btnenrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnenrere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1)
                                .addGap(269, 269, 269)))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnenrere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdireccioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccioActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        modificar();
        listar();
        nou();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnafegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnafegirActionPerformed
        Agregar();
        listar();
        nou();
    }//GEN-LAST:event_btnafegirActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtcifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcifActionPerformed

    private void txttelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonActionPerformed

    private void tauladadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tauladadesMouseClicked
        int fila=tauladades.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(null,"Entitat no seleccionada");
        } else {
            id=Integer.parseInt((String)tauladades.getValueAt(fila,0).toString());
            String nom=(String)tauladades.getValueAt(fila, 1);
            String localitat=(String)tauladades.getValueAt(fila, 2);
            String direccio=(String)tauladades.getValueAt(fila, 3);
            String telefon=(String)tauladades.getValueAt(fila, 4);
            String cif=(String)tauladades.getValueAt(fila, 5);
            String email=(String)tauladades.getValueAt(fila, 6);
            String estat=(String)tauladades.getValueAt(fila, 7);
            //txtid.setText(""+id);
            txtnom.setText(nom);
            txtlocalitat.setText(localitat);
            txtdireccio.setText(direccio);
            txttelefon.setText(telefon);
            txtcif.setText(cif);
            txtemail.setText(email);
            
        }
    }//GEN-LAST:event_tauladadesMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        eliminar();
        listar();
        nou();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnnouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouActionPerformed
        nou();
    }//GEN-LAST:event_btnnouActionPerformed

    private void btnnou1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnou1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnou1ActionPerformed

    private void btnenrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenrereActionPerformed
            //creem la nova finestra LlistatJFrame
        JFrameMenuPrincipal obj = new JFrameMenuPrincipal(); 	
        //la fem visible
        obj.setVisible(true);           
        //eliminem la finestra actual
        dispose(); 
     
    }//GEN-LAST:event_btnenrereActionPerformed
   void modificar(){
       String nom=txtnom.getText();
       String localitat=txtlocalitat.getText();
       String direccio=txtdireccio.getText();
       String telefon=txttelefon.getText();
       String cif=txtcif.getText();
       String email=txtemail.getText();
       String sql="update empresas set nom='"+nom+"',localitat='"+localitat+"',direccio='"+direccio+"',telefon='"+telefon+"',cif='"+cif+"',email='"+email+"' where id="+id;
       if (nom.equals("")||localitat.equals("")||direccio.equals("")||telefon.equals("")||cif.equals("")||email.equals("")){
           JOptionPane.showMessageDialog(null,"Alguns camps estan buits");
       } else {
           try {
              cn=con.getConnection();
              st=cn.createStatement();
              st.executeUpdate(sql);
              JOptionPane.showMessageDialog(null,"S'han guardat els canvis correctament");
              llimpiarTaula();
           } catch (Exception e){
               
           }
       }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpreses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpreses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpreses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpreses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmpreses().setVisible(true);
            }
        });
    }
    void listar (){
        String sql ="select * from empresas";
        try {
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]empreses=new Object [8];
            modelo =(DefaultTableModel)tauladades.getModel();
            while (rs.next()) {
                empreses[0]=rs.getInt("id");
                empreses[1]=rs.getString("nom");
                empreses[2]=rs.getString("localitat");
                empreses[3]=rs.getString("direccio");
                empreses[4]=rs.getString("telefon");
                empreses[5]=rs.getString("cif");
                empreses[6]=rs.getString("email");
                empreses[7]=rs.getString("estat");
                modelo.addRow(empreses);
            }
            tauladades.setModel(modelo);
        } catch (Exception e){
            
        }
    }
    void Agregar(){
        String nom=txtnom.getText();
        String localitat=txtlocalitat.getText();
        String direccio=txtdireccio.getText();
        String telefon=txttelefon.getText();
        String cif=txtcif.getText();
        String email=txtemail.getText();   
        
        if (nom.equals("")||localitat.equals("")||direccio.equals("")||telefon.equals("")||cif.equals("")||email.equals("")) {
            JOptionPane.showMessageDialog(null,"Alguns camps estan buits");
        } else {
            String sql="insert into empresas (nom,localitat,direccio,telefon,cif,email)values('"+nom+"','"+localitat+"','"+direccio+"','"+telefon+"','"+cif+"','"+email+"')";
            try {
              cn=con.getConnection();
              st=cn.createStatement();
              st.executeUpdate(sql);
              JOptionPane.showMessageDialog(null,"Entitat afegida correctament");
              llimpiarTaula();
            } catch (Exception e) {
                
            }
        }
    }
    void llimpiarTaula() {
        for (int i=0;i<=tauladades.getRowCount();i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
    void eliminar() {
        int seleccionat=tauladades.getSelectedRow();
        if(seleccionat==-1){
            JOptionPane.showMessageDialog(null,"Es te que seleccionar una empresa per a poder eliminar-la");
            
        } else {
            String sql="delete from empresas where id="+id;
            try {
               cn=con.getConnection();
               st=cn.createStatement();
               st.executeUpdate(sql);
               JOptionPane.showMessageDialog(null,"L'empresa a sigut eliminada correctament");
               llimpiarTaula();
            } catch (Exception e){
                
            }
        }
    }
    void nou() {
        txtnom.setText("");
        txtlocalitat.setText("");
        txtdireccio.setText("");
        txttelefon.setText("");
        txtcif.setText("");
        txtemail.setText("");
        txtnom.requestFocus();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnafegir;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnenrere;
    private javax.swing.JButton btnnou;
    private javax.swing.JButton btnnou1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tauladades;
    private javax.swing.JLabel telefon;
    private javax.swing.JTextField txtcif;
    private javax.swing.JTextField txtdireccio;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtlocalitat;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txttelefon;
    // End of variables declaration//GEN-END:variables
}
